CREATE TABLE IF NOT EXISTS `market_prices` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `item` VARCHAR(50) NOT NULL,
    `price` INT NOT NULL,
    `last_update` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

